spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  hide-navbar: true
  heartbeat-rate: 100000
  heartbeat-timeout: 600000
  port: 8080
  authentication: simple
  admin-groups: scientists
  container-wait-time: 200000
  # Example: 'simple' authentication configuration
  users:
  - name: gettrix
    password: matrix
    groups: scientists
  - name: public
    password: public
    group: scientists
  - name: E01
    password: hegu
    groups: scientists
  - name: E05
    password: isos
    groups: scientists
  - name: guest
    password: guest
    groups: scientists
  - name: I2MC11
    password: bepa
    groups: scientists
  - name: UNH
    password: UNH
    groups: scientists
  - name: admindev
    password: trixdev
    groups: scientists
  - name: TRIX
    password: YALI
    groups: scientists
  # Example: 'ldap' authentication configuration
  ldap:
    url: ldap://ldap.forumsys.com:389/dc=example,dc=com
    user-dn-pattern: uid={0}
    group-search-base:
    group-search-filter: (uniqueMember={0})
    manager-dn: cn=read-only-admin,dc=example,dc=com
    manager-password: password
  authentication: simple
  support:
    mail-to-address: franck.soubes@inra.fr
  container-log-path: ./container-logs
  #container-env-file:
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians]
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: scientists
  - id: matrix
    display-name: MATRiX appl
    description: Application which allow users to explore microarray data
    container-cmd: ["R", "-e", "shiny::runApp('/root/MA_Trix_App')"]
    container-volumes:  [ "/home/fsoubes/project:/root/MA_Trix_App/data" , "/home/fsoubes/chat:/root/MA_Trix_App/chat" ]
    container-image: openanalytics/shinyproxy-template
    access-groups: [scientists, mathematicians]
  - id: matrixdev
    display-name: MATRiX appl
    description: Application which allow users to explore microarray data
    container-cmd: ["R", "-e", "shiny::runApp('/root/MA_Trix_App')"]
    container-volumes:  [ "/home/fsoubes/project:/root/MA_Trix_App/data" , "/home/fsoubes/chat:/root/MA_Trix_App/chat" ]
    container-image: matrixdev
    access-groups: [scientists, mathematicians]

logging:
  file:
    shinyproxy.log
